config/routes.rb
Rails.application.routes.draw do
 resources :posts do
 resources :comments do
 	resources :replies
end
 end# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
	belongs_to :doctor
	belongs_to :patient
	validate :check
	def check
		p_inf=Patient.where(id: patient_id)
		is_doc=p_inf[0].role
		if is_doc
			d_inf=Doctor.where(id: doctor_id)
			doc_id=d_inf[0].udid
			pat_id=p_inf[0].upid
			if  doc_id == pat_id
				errors.add(error:"Doctor and Patient can be same person")
            end
        end
	end
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    has_many :replies,dependent: :destroy
	has_many :likes,as: :likeable,dependent: :destroy
end

app/models/doctor.rb
class Doctor < ApplicationRecord
	has_many :appointments
	has_many :patients, through: :appointments
	
end

app/models/employee.rb
class Employee < ApplicationRecord
	has_many :events
    
    
	
	end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :employee


  validate :manager
	def manager
		e_rec=Employee.where(id: employee_id)
		i_man=e_rec[0].role
		if i_man != "manager"
			errors.add(error: "Action denied! you can't create event ")
		end
	end
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :likeable,polymorphic:true
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_many :appointments
	has_many :doctors, through: :appointments

end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments,dependent: :destroy
	has_many :likes ,as: :likeable,dependent: :destroy
end

app/models/reply.rb
class Reply < ApplicationRecord
belongs_to :comment
has_many :likes,as: :likeable, dependent: :destroy
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def edit
    @post=Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end
  def show
    @replies=Reply.all
  end
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end
  def update
  	@post=Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  	 if @comment.update(comment_params)
  	 	redirect_to post_path(@post)
  	 else
  	  	render 'comments/edit'
  	 end
  end

def destroy
    @post=Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
end
 
  private
    def comment_params
      params.require(:comment).permit(:title, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
		def index
		    @posts=Post.all	
		end

		def show
			@post=Post.find(params[:id])
		end

		def new
			@post=Post.new
		end

		def edit
			@post=Post.find(params[:id])
		end


		def create
			@post =Post.new(post_params)
			if @post.save
			    redirect_to @post
		    else
		    	render 'new'
		    end
		end

		def update
		    @post = Post.find(params[:id])
		 
		    if @post.update(post_params)
		        redirect_to @post
		    else
		        render 'edit'
		    end
		 end

		def destroy
		    @post = Post.find(params[:id])
		    @post.destroy
		 
		    redirect_to posts_path
		end

		private
		def post_params
			params.require(:post).permit(:title,:body)
		end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
def edit
    @post=Post.find(params[:post_id])
    @comment = @post.comments.find(params[:comment_id])
	@reply = @comment.replies.find(params[:id])
end

def create
    @post=Post.find(params[:post_id])
    @comment = @post.comments.find(params[:comment_id])
	  @reply=@comment.replies.create(reply_params)
    redirect_to post_comment_path(@comment)
  end
  def update
  	@post=Post.find(params[:post_id])
    @comment = @post.comments.find(params[:comment_id])
	@reply = @comment.replies.find(params[:id])
	if @reply.update(reply_params)
		redirect_to comment_path(@comment) 
	else
		render 'reply/form'
	end
  end
  def destroy
    @post=Post.find(params[:post_id])
    @comment = @post.comments.find(params[:comment_id])
	@reply = @comment.replies.find(params[:id])
    @reply.destroy
    redirect_to comment_path(@comment)
  end
 
  private
    def reply_params
      params.require(:reply).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/comments/_comment.html.erb
    <% @post.comments.each do |comment| %>
      <p>
        <strong>Commenter:</strong>
          <%= comment.title %>
      </p>
 
      <p>
        <strong>Comment:</strong>
          <%= comment.body %>
      </p>
      <p>
      <%= link_to 'Destroy Comment', [comment.post, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
      </p>
      <p>
      <%= link_to 'Edit Comment' ,edit_post_comment_path(comment.post,comment) %>            
      </p>
      <p>
        <%= link_to 'Reply',  post_comment_path(comment.id) %>
      </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h1>EDIT A COMMENT</h1>
<%= form_for([@post, @comment]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', post_path %> 

app/views/comments/show.html.erb
<%= form_for :reply do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<% @replies.each do |reply| %>
      <p>
        <strong>replier:</strong>
          <%= reply.title %>
      </p>
 
      <p>
        <strong>reply:</strong>
          <%= reply.body %>
      </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assign</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
 
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/posts/edit.html.erb
<h1>Edit a Post</h1>
<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing articles</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th colspan="2"></th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.body %></td>
      <td><%= link_to 'Show', post_path(post) %></td>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <td><%= link_to 'Destroy', post_path(post),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td
    </tr>
  <% end %>
</table>
<%= link_to 'New post', new_post_path %>

app/views/posts/new.html.erb
<h1>Posts</h1>
<h2>CREATE A POST</h2>


<%= render 'form' %>
<% end %>

app/views/posts/show.html.erb
<h1>SHOWING POSTS</h1>
<p>
    <strong>Title:</strong>
    <%= @post.title %>
</p>
 
<p>
    <strong>Body:</strong>
    <%= @post.body %>
</p>

  <h2>COMMENTS</h2>
    <%= render @post.comments %>
  <h2>Add a comment:</h2>
    <%= render 'comments/form'%>

  <%= link_to 'Edit', edit_post_path(@post) %>
  <%= link_to 'Back', posts_path %>

app/views/replies/_form.html.erb
<%= form_for @reply do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/replies/_reply.html.erb
<% @post.comments.replies.each do |reply| %>
      <p>
        <strong>Reply:</strong>
          <%= reply.title %>
      </p>
 
      <p>
        <strong>Reply:</strong>
          <%= reply.body %>
      </p>
      <p>
      <%= link_to 'Destroy Reply', [reply.comment, reply],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
      </p>

app/views/replies/edit.html.erb
<h1>EDIT A REPLY</h1>
<%= form_for([@post, @comment, @reply]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', post_path %>

app/views/replies/new.html.erb
<%= form_for :reply,url: post_comment_replies do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>